embed_assets: on

javascripts:
  app:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery.mobile-1.0a4.1.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/application.js

stylesheets:
  app:
    #- public/stylesheets/reset.css
    - public/stylesheets/jquery.mobile-1.0a4.1.css
    - public/stylesheets/application.css
